[[redirects]]
  from = "https://schnitzelsallskapet.se/*"
  to = "https://xn--schnitzelsllskapet-utb.se/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://schnitzelsallskapet.netlify.com/*"
  to = "https://xn--schnitzelsllskapet-utb.se/:splat"
  status = 301
  force = true